spring:
  application:
    name: attendance
  config:
    activate:
      on-profile: local

  # Security -----------------------------------------------------------------------------------------
  security:
    oauth2:
      client:
        google:
          client-id: clientId
          client-secret: clientSecret
          redirect-uri: redirect-uri
          authorization-grant-type: authorization_code
          scope:
            - email
            - profile
          url:
            access-token: https://oauth2.googleapis.com/token
            profile: https://www.googleapis.com/userinfo/v2/me

  # H2 Database --------------------------------------------------------------------------------------

  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:~/test;DB_CLOSE_DELAY=-1;MODE=MariaDB;DATABASE_TO_LOWER=FALSE;CASE_INSENSITIVE_IDENTIFIERS=FALSE;
      username: sa
      connection-init-sql: SELECT 1
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA ----------------------------------------------------------------------------------------------

  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        generate_statistics: false
        globally_quoted_identifiers: true
    defer-datasource-initialization: true

  # Redis --------------------------------------------------------------------------------------------

  cache:
    type: redis
  data:
    redis:
      client-type: lettuce
      host: localhost
      port: 6379
      embedded:
        enabled: true
        daemonize: false
        append-only: false
        max-memory:
          capacity: 128
          unit: mb

# P6Spy --------------------------------------------------------------------------------------------

decorator:
  datasource:
    p6spy:
      enable-logging: true

# Servlet ------------------------------------------------------------------------------------------

server:
  port: 8100
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Logging ------------------------------------------------------------------------------------------

logging:
  charset:
    console: UTF-8
  level:
    root: info
    sql: debug
    p6spy: info
    co.oneplat.teamkeeper: debug
